### ISSUE TITLE
Set temperature of DECT 301

### ISSUE THREAD

**Issue by vio2000** [bashGroup/node-red-contrib-fritz#23]
Hi,
Is there any possibility to set the temperature of a DECT 301? 
I was trying, but none of my approaches would work.
Thanks for helping
VIO

**Comment by elpatron68** [comment]
https://www.npmjs.com/package/fritzapi should show an apporach, altough, I didn´t have a deeper look into it.

**Comment by mapero** [comment]
I do not have a thermostat DECT 301. But from looking in the fritzbox API documentation, there is no function to set the temperature. fritzapi is using a different interface.

Since I currently do not have such a device and there is an alternative solution. I suggest to use node-red-contrib-fritzapi for controlling DECT 301.
