### ISSUE TITLE
Lookup callee isn't working for local numbers

### ISSUE THREAD

**Issue by wichtelsbr** [bashGroup/node-red-contrib-fritz#41]
Lookup for Callee in Phonebook isn't working. It seems the country evaluation interferes with the phonebook for Callee.

msg : string[54]
"The provided number 9xxxxx2 is not valid for region DE"

**Comment by ozett** [comment]
i have a similiar respone from the lookup with my fritzbox 7580 and os 7.12:
```
The invalid phonebook number 500@hd-telefonie.avm.de for region DE will be ignored: Error: The string supplied did not seem to be a phone number
```
could this be fixed in the node-red-contrib-fritz ?

**Comment by mapero** [comment]
I will have a look at the issue the next week.

**Comment by mapero** [comment]
> Lookup for Callee in Phonebook isn't working. It seems the country evaluation interferes with the phonebook for Callee.
> 
> msg : string[54]
> "The provided number 9xxxxx2 is not valid for region DE"

So this needs some more effort to resolve this. The "Lookup" function is using "google-libphonenumber" to normalize the phone numbers. This step is needed so that, e.g. 01234-5432 matches +4912345432. It seems like the library does not really work with "local numbers". It does provide a function to check if a number might be a local number, but it does not seem to work correctly. So the idea would be to implement a fallback, when the input number could not be parsed to make a simple string compare. But I am currently quite busy and it will take some time to implement.

**Comment by mapero** [comment]
1.5.0 contains an fallback, if the number can not be normalized a normal string compare will be performed for lookup.
